displayName=Swarmer
author=javlanoob
support=https://github.com/javlanoob/swarmer
description=Hides scarab swarms at Kephri as soon as they're hit
tags=toa,tombs,amascut,kephri,swarm,scarab,death,indicator,hide,highlight,party
plugins=com.swarmer.SwarmerPlugin
build=standard
