displayName=Swarmer
author=javlanoob
support=https://github.com/javlanoob/swarmer
description=Hide dead scarab swarms and show wave numbers in ToA
tags=combat,npcs,pvm,toa,swarm,scarab,tombs,amascut,overlay
plugins=com.javlanoob.SwarmerPlugin
